# Generated by Django 3.2.20 on 2023-07-11 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('time', models.CharField(default='9999', max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('color', models.IntegerField(default=0)),
            ],
        ),
    ]
